version: '3.8'

services:
  web:
    image: my-wishlist-app
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: wishlist
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 4941
      MYSQL_DATABASE: wishlist

volumes:
  db-data:
